# Generated by Django 2.2.6 on 2019-10-30 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aptitude',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qno', models.IntegerField(blank=True, null=True)),
                ('question', models.TextField(blank=True, null=True)),
                ('option1', models.CharField(blank=True, max_length=100, null=True)),
                ('option2', models.CharField(blank=True, max_length=100, null=True)),
                ('option3', models.CharField(blank=True, max_length=100, null=True)),
                ('option4', models.CharField(blank=True, max_length=100, null=True)),
                ('answer', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GeneralKnowledge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qno', models.IntegerField(blank=True, null=True)),
                ('question', models.TextField(blank=True, null=True)),
                ('option1', models.CharField(blank=True, max_length=100, null=True)),
                ('option2', models.CharField(blank=True, max_length=100, null=True)),
                ('option3', models.CharField(blank=True, max_length=100, null=True)),
                ('option4', models.CharField(blank=True, max_length=100, null=True)),
                ('answer', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reasogning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qno', models.IntegerField(blank=True, null=True)),
                ('question', models.TextField(blank=True, null=True)),
                ('option1', models.CharField(blank=True, max_length=100, null=True)),
                ('option2', models.CharField(blank=True, max_length=100, null=True)),
                ('option3', models.CharField(blank=True, max_length=100, null=True)),
                ('option4', models.CharField(blank=True, max_length=100, null=True)),
                ('answer', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
