# Generated by Django 2.2.6 on 2019-11-02 06:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0002_auto_20191102_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_aptitude_sample',
            name='created_by',
            field=models.ForeignKey(blank=True, default='Admin', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='add_generalknowledge_sample',
            name='created_by',
            field=models.ForeignKey(blank=True, default='Admin', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='add_reasogning_sample',
            name='created_by',
            field=models.ForeignKey(blank=True, default='Admin', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
