# Generated by Django 2.2.6 on 2019-10-31 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='profile_image',
            field=models.FileField(blank=True, null=True, upload_to='pics/'),
        ),
    ]
